//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScooterRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int ID { get; set; }
        public int VechicleID { get; set; }
        public int UserID { get; set; }
        public int TypeID { get; set; }
        public System.DateTime Start_time { get; set; }
        public Nullable<System.DateTime> End_time { get; set; }
        public int StatusID { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual TypeOfMaintenance TypeOfMaintenance { get; set; }
        public virtual User User { get; set; }
        public virtual Vechicles Vechicles { get; set; }
    }
}
