//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScooterRental
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScooterRentalEntities : DbContext
    {
        public ScooterRentalEntities()
            : base("name=ScooterRentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Maintenance> Maintenance { get; set; }
        public virtual DbSet<Parking> Parking { get; set; }
        public virtual DbSet<Rentals> Rentals { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tariffs> Tariffs { get; set; }
        public virtual DbSet<TypeOfMaintenance> TypeOfMaintenance { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vechicles> Vechicles { get; set; }
        public virtual DbSet<Vechicles_Models> Vechicles_Models { get; set; }
        public virtual DbSet<Vechicles_Types> Vechicles_Types { get; set; }
    }
}
