//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScooterRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int VechiclesID { get; set; }
        public string Text { get; set; }
        public int Rate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Vechicles Vechicles { get; set; }
    }
}
