//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScooterRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vechicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vechicles()
        {
            this.Maintenance = new HashSet<Maintenance>();
            this.Rentals = new HashSet<Rentals>();
            this.Review = new HashSet<Review>();
        }
    
        public int ID { get; set; }
        public int TypeID { get; set; }
        public int ModelID { get; set; }
        public bool Status { get; set; }
        public decimal Rating { get; set; }
        public int ParkingID { get; set; }
        public int Energy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenance { get; set; }
        public virtual Parking Parking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rentals> Rentals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
        public virtual Vechicles_Types Vechicles_Types { get; set; }
        public virtual Vechicles_Models Vechicles_Models { get; set; }
    }
}
